apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsfront-config
data:
  config.json: >
    {
      "front_ip"   : "0.0.0.0",
      "front_port" : 443,

      "server_ip"   : "<tbd>",
      "server_port" : 443,
      
      "back_ip"   : "0.0.0.0"
    }
  
  key.pem: |
    -----BEGIN PRIVATE KEY-----
    <tbd>
    -----END PRIVATE KEY-----

  cert.pem: |
    -----BEGIN CERTIFICATE-----
    <tbd>
    -----END CERTIFICATE-----

