apiVersion: v1
kind: Service
metadata:
  name: tlsfront-backend-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.115.30.245
  selector:
    app: tlsfront-backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: tlsfront-web-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.115.30.245
  selector:
    app: tlsfront-web
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

