apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsfront-testrail-configmap
data:
  config.json: >
    {
      "app_id" : "tlsfront-testrail",

      "front_ip"   : "0.0.0.0",
      "front_port" : 443,

      "server_ip"   : "10.22.0.226",
      "server_port" : 443,
      "server_ssl"  : 1,

      "stats_ip"   : "10.115.30.245",
      "stats_port" : 7000,

      "monitor_ip"   : "10.115.78.80",
      "monitor_port" : 7500,

      "back_ip"   : "0.0.0.0"
    }
  
  key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDR3fjuUmy2VVzD
    uHvgHw4UmJn/J3agX6maxT6Q1SeLFGC7Qz3v0Tk3cJy9W8GwCed42CnMrbcfSTF1
    +USRXgj2R43ofaSWQe8wUs6nfyYlwB2zni3lalWFiU44b1Px07bPuRxjtOiLSNDB
    /FXPt3lwSL/NlPGDa2W0tRhnMLwgkE1jrNnsNG1jseWEVW/AIcyFbf68s/JCIj3F
    UY/249Gj7tEnJa9LGj4zMzXJcNvKW9EPiclc3+yDCDQL9y64ybYpzl9ke2GGMJpm
    75IezTVAWPeTkJEgFNj+8YxODEt68YaFL8lKWe/HVld07HVkjZFu8ylivtf9svXV
    2Q5076qNAgMBAAECggEARbT84evuwAFKdpfoTWEDREQLonxxIoOjygyJ44FpSQDT
    wF9tSyKrZoa5CQxZISepArKJ77ojgPjGvPC2nbImN+c8c2SILoBn+h0HFwtcmF1f
    gDGh/Pl8voYEvSn9L+2qYwSRMWz9cIYXENfHiN7gLzN6wcYfEg+yEHu2R1AgrI+n
    jmqCgxPwgMS/zVrHiUVMFNqBMx/SDvFaKlvJ4I9apQJGwDssHzlmZYmCU+pGRR/4
    0+zzfCTzsNUVEa63SWf1bq7lL65dGT7L5/LVvsTma9CyrYAeoxErrFhfciqt3mAR
    Cs0a7gOdVewWkjdoKR9H+6TNvl8/ojsUdtWqs9yLAQKBgQDwrFL6UADxYaDzD6ie
    Wf6TVBoyOLR7DFx4sbeogWjRT+Wu89IznVtvsoR+qHyM2bfY3XX9OTaIoJBK4oZi
    62KcoisvGzxHjW2HsAZ4keEg6ZviyB39aw+AkkLV30ibkvsQ8xjMjsvoDk9kbw+O
    SkULTLKQDY9hHJX7qXuFGd4U9QKBgQDfO2tcrMcnFvwl5PrZcUbRZM6xutYaLSu+
    KjSG4OiqGMywJHA4qdKvp+qNwzGH3ghhVaq2rOx5LGiZlQbw9rbNPpP+6MUE/uz5
    O5UcWqaVyegYTAa1ih8LfmqlX6+lo36asyJ991CN9hH/jk6fB2ERD2EiqBui5I/2
    SxsAcmkAOQKBgE0rlDe663J6kXcecDzGMoDfGL89u3ExF32DzpXzWL601brxZ1cx
    f54jKaTLNZScQv0AldKqQ7gvc9TvKZQSUb5TqXEjVILE8Hfvk0OZ0wwQm/FtpWAa
    sg/R1ihpvghUariWmj8NEojH/eEAU4aWfekPoLnb/ztuRRE62OZm0vT5AoGAMDmX
    8gdpZqpygoU7I+py0B2lAYRJaJJFlulrO5Au80A0SAE3NSaK22O9Ki727lErIkvt
    e1VUKMFNP5CQVVIXH7PbKQCEP5YK/7S9e8ihoE5kE4upD2LtXgBLbbqEKZZubWEx
    nGDnSCPWs4y8s2JWt+bIp0IF5mTWLPEAvlH5GRECgYEAlUBmofySCCOg1C8WaGTK
    P+gYl7uITbyUoSHsdvcVhP4gfXywixRc3Sha1lJVCDO1NoQfWgf0+p8Dsd7TP6P8
    +IX3sj7INi6JrbY5lcISelqTpzVFoPeFu0REfUHCmOCy+PGt3TedKqN2v+nzB1JO
    Jrg3tqr1//McKrbUNZha5LU=
    -----END PRIVATE KEY-----

  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIJAPkXL2dCDVVNMA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV
    BAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExEDAOBgNV
    BAoMB0dpZ2Ftb24xDDAKBgNVBAsMA1JuRDEdMBsGA1UEAwwUdGVzdHJhaWwuZ2ln
    YW1vbi5jb20wHhcNMjExMDI0MDY0OTI3WhcNMzExMDIyMDY0OTI3WjBvMQswCQYD
    VQQGEwJVUzELMAkGA1UECAwCQ0ExFDASBgNVBAcMC1NhbnRhIENsYXJhMRAwDgYD
    VQQKDAdHaWdhbW9uMQwwCgYDVQQLDANSbkQxHTAbBgNVBAMMFHRlc3RyYWlsLmdp
    Z2Ftb24uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0d347lJs
    tlVcw7h74B8OFJiZ/yd2oF+pmsU+kNUnixRgu0M979E5N3CcvVvBsAnneNgpzK23
    H0kxdflEkV4I9keN6H2klkHvMFLOp38mJcAds54t5WpVhYlOOG9T8dO2z7kcY7To
    i0jQwfxVz7d5cEi/zZTxg2tltLUYZzC8IJBNY6zZ7DRtY7HlhFVvwCHMhW3+vLPy
    QiI9xVGP9uPRo+7RJyWvSxo+MzM1yXDbylvRD4nJXN/sgwg0C/cuuMm2Kc5fZHth
    hjCaZu+SHs01QFj3k5CRIBTY/vGMTgxLevGGhS/JSlnvx1ZXdOx1ZI2RbvMpYr7X
    /bL11dkOdO+qjQIDAQABo1AwTjAdBgNVHQ4EFgQUZEy+VWCtPt5hAJcjMd+mrSMr
    GE0wHwYDVR0jBBgwFoAUZEy+VWCtPt5hAJcjMd+mrSMrGE0wDAYDVR0TBAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAfX/d1pQT6O7lwL1IeDNr6HsDdb21av6rmBdz
    +LbjQJqjxqPSlgjHlNxH14A6MEmbZL0VN9hUAXYpF+6L0SHf77siudSw9zDk9wog
    bjeK4uynOaM4hLd65kmzTtCbyRi6+LTEAPto4QLwsI9YQahTkrVQl/ZfDj41VpH5
    jWtVFB9yoMUEDh9v0g41iX2esRD+ROP2pMKSRDqTiovMSuba3Qa2dciKnn5KcBYF
    R+ngq8dYFgxmjJQ/S9Q82dc/MJFh4FgV2UKt1SUiRGdppuA5o9+LHAB7xYZ4faQI
    tdEq5o1qLLAva6zdiny+Rll6eYMGf0BAEo5oHokc9Wdc3FoVxQ==
    -----END CERTIFICATE-----


---



apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsfront-web-configmap
data:
  config.json: >
    {
      "webui_ip"  : "0.0.0.0",
      "webui_port"  : 8888,

      "stats_port" : 7000,

      "stats_ticks" : 3
    }



---



apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsserver-configmap
data:
  config.json: >
    {
      "app_id" : "tlsserver",


      "server_ip"   : "0.0.0.0",
      "server_port" : 88,
      "server_ssl"  : 0,

      "stats_ip"   : "10.115.30.245",
      "stats_port" : 7000,

      "send_recv_len" : 102400
    }
  
  key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDR3fjuUmy2VVzD
    uHvgHw4UmJn/J3agX6maxT6Q1SeLFGC7Qz3v0Tk3cJy9W8GwCed42CnMrbcfSTF1
    +USRXgj2R43ofaSWQe8wUs6nfyYlwB2zni3lalWFiU44b1Px07bPuRxjtOiLSNDB
    /FXPt3lwSL/NlPGDa2W0tRhnMLwgkE1jrNnsNG1jseWEVW/AIcyFbf68s/JCIj3F
    UY/249Gj7tEnJa9LGj4zMzXJcNvKW9EPiclc3+yDCDQL9y64ybYpzl9ke2GGMJpm
    75IezTVAWPeTkJEgFNj+8YxODEt68YaFL8lKWe/HVld07HVkjZFu8ylivtf9svXV
    2Q5076qNAgMBAAECggEARbT84evuwAFKdpfoTWEDREQLonxxIoOjygyJ44FpSQDT
    wF9tSyKrZoa5CQxZISepArKJ77ojgPjGvPC2nbImN+c8c2SILoBn+h0HFwtcmF1f
    gDGh/Pl8voYEvSn9L+2qYwSRMWz9cIYXENfHiN7gLzN6wcYfEg+yEHu2R1AgrI+n
    jmqCgxPwgMS/zVrHiUVMFNqBMx/SDvFaKlvJ4I9apQJGwDssHzlmZYmCU+pGRR/4
    0+zzfCTzsNUVEa63SWf1bq7lL65dGT7L5/LVvsTma9CyrYAeoxErrFhfciqt3mAR
    Cs0a7gOdVewWkjdoKR9H+6TNvl8/ojsUdtWqs9yLAQKBgQDwrFL6UADxYaDzD6ie
    Wf6TVBoyOLR7DFx4sbeogWjRT+Wu89IznVtvsoR+qHyM2bfY3XX9OTaIoJBK4oZi
    62KcoisvGzxHjW2HsAZ4keEg6ZviyB39aw+AkkLV30ibkvsQ8xjMjsvoDk9kbw+O
    SkULTLKQDY9hHJX7qXuFGd4U9QKBgQDfO2tcrMcnFvwl5PrZcUbRZM6xutYaLSu+
    KjSG4OiqGMywJHA4qdKvp+qNwzGH3ghhVaq2rOx5LGiZlQbw9rbNPpP+6MUE/uz5
    O5UcWqaVyegYTAa1ih8LfmqlX6+lo36asyJ991CN9hH/jk6fB2ERD2EiqBui5I/2
    SxsAcmkAOQKBgE0rlDe663J6kXcecDzGMoDfGL89u3ExF32DzpXzWL601brxZ1cx
    f54jKaTLNZScQv0AldKqQ7gvc9TvKZQSUb5TqXEjVILE8Hfvk0OZ0wwQm/FtpWAa
    sg/R1ihpvghUariWmj8NEojH/eEAU4aWfekPoLnb/ztuRRE62OZm0vT5AoGAMDmX
    8gdpZqpygoU7I+py0B2lAYRJaJJFlulrO5Au80A0SAE3NSaK22O9Ki727lErIkvt
    e1VUKMFNP5CQVVIXH7PbKQCEP5YK/7S9e8ihoE5kE4upD2LtXgBLbbqEKZZubWEx
    nGDnSCPWs4y8s2JWt+bIp0IF5mTWLPEAvlH5GRECgYEAlUBmofySCCOg1C8WaGTK
    P+gYl7uITbyUoSHsdvcVhP4gfXywixRc3Sha1lJVCDO1NoQfWgf0+p8Dsd7TP6P8
    +IX3sj7INi6JrbY5lcISelqTpzVFoPeFu0REfUHCmOCy+PGt3TedKqN2v+nzB1JO
    Jrg3tqr1//McKrbUNZha5LU=
    -----END PRIVATE KEY-----

  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIJAPkXL2dCDVVNMA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV
    BAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExEDAOBgNV
    BAoMB0dpZ2Ftb24xDDAKBgNVBAsMA1JuRDEdMBsGA1UEAwwUdGVzdHJhaWwuZ2ln
    YW1vbi5jb20wHhcNMjExMDI0MDY0OTI3WhcNMzExMDIyMDY0OTI3WjBvMQswCQYD
    VQQGEwJVUzELMAkGA1UECAwCQ0ExFDASBgNVBAcMC1NhbnRhIENsYXJhMRAwDgYD
    VQQKDAdHaWdhbW9uMQwwCgYDVQQLDANSbkQxHTAbBgNVBAMMFHRlc3RyYWlsLmdp
    Z2Ftb24uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0d347lJs
    tlVcw7h74B8OFJiZ/yd2oF+pmsU+kNUnixRgu0M979E5N3CcvVvBsAnneNgpzK23
    H0kxdflEkV4I9keN6H2klkHvMFLOp38mJcAds54t5WpVhYlOOG9T8dO2z7kcY7To
    i0jQwfxVz7d5cEi/zZTxg2tltLUYZzC8IJBNY6zZ7DRtY7HlhFVvwCHMhW3+vLPy
    QiI9xVGP9uPRo+7RJyWvSxo+MzM1yXDbylvRD4nJXN/sgwg0C/cuuMm2Kc5fZHth
    hjCaZu+SHs01QFj3k5CRIBTY/vGMTgxLevGGhS/JSlnvx1ZXdOx1ZI2RbvMpYr7X
    /bL11dkOdO+qjQIDAQABo1AwTjAdBgNVHQ4EFgQUZEy+VWCtPt5hAJcjMd+mrSMr
    GE0wHwYDVR0jBBgwFoAUZEy+VWCtPt5hAJcjMd+mrSMrGE0wDAYDVR0TBAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAfX/d1pQT6O7lwL1IeDNr6HsDdb21av6rmBdz
    +LbjQJqjxqPSlgjHlNxH14A6MEmbZL0VN9hUAXYpF+6L0SHf77siudSw9zDk9wog
    bjeK4uynOaM4hLd65kmzTtCbyRi6+LTEAPto4QLwsI9YQahTkrVQl/ZfDj41VpH5
    jWtVFB9yoMUEDh9v0g41iX2esRD+ROP2pMKSRDqTiovMSuba3Qa2dciKnn5KcBYF
    R+ngq8dYFgxmjJQ/S9Q82dc/MJFh4FgV2UKt1SUiRGdppuA5o9+LHAB7xYZ4faQI
    tdEq5o1qLLAva6zdiny+Rll6eYMGf0BAEo5oHokc9Wdc3FoVxQ==
    -----END CERTIFICATE-----


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsfront-tlsserver-configmap
data:
  config.json: >
    {
      "app_id" : "tlsfront-tlsserver",

      "front_ip"   : "0.0.0.0",
      "front_port" : 89,

      "server_ip"   : "10.115.30.245",
      "server_port" : 88,
      "server_ssl"  : 0,

      "stats_ip"   : "10.115.30.245",
      "stats_port" : 7000,

      "monitor_ip"   : "10.115.78.80",
      "monitor_port" : 7600,

      "back_ip"   : "0.0.0.0"
    }
  
  key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDR3fjuUmy2VVzD
    uHvgHw4UmJn/J3agX6maxT6Q1SeLFGC7Qz3v0Tk3cJy9W8GwCed42CnMrbcfSTF1
    +USRXgj2R43ofaSWQe8wUs6nfyYlwB2zni3lalWFiU44b1Px07bPuRxjtOiLSNDB
    /FXPt3lwSL/NlPGDa2W0tRhnMLwgkE1jrNnsNG1jseWEVW/AIcyFbf68s/JCIj3F
    UY/249Gj7tEnJa9LGj4zMzXJcNvKW9EPiclc3+yDCDQL9y64ybYpzl9ke2GGMJpm
    75IezTVAWPeTkJEgFNj+8YxODEt68YaFL8lKWe/HVld07HVkjZFu8ylivtf9svXV
    2Q5076qNAgMBAAECggEARbT84evuwAFKdpfoTWEDREQLonxxIoOjygyJ44FpSQDT
    wF9tSyKrZoa5CQxZISepArKJ77ojgPjGvPC2nbImN+c8c2SILoBn+h0HFwtcmF1f
    gDGh/Pl8voYEvSn9L+2qYwSRMWz9cIYXENfHiN7gLzN6wcYfEg+yEHu2R1AgrI+n
    jmqCgxPwgMS/zVrHiUVMFNqBMx/SDvFaKlvJ4I9apQJGwDssHzlmZYmCU+pGRR/4
    0+zzfCTzsNUVEa63SWf1bq7lL65dGT7L5/LVvsTma9CyrYAeoxErrFhfciqt3mAR
    Cs0a7gOdVewWkjdoKR9H+6TNvl8/ojsUdtWqs9yLAQKBgQDwrFL6UADxYaDzD6ie
    Wf6TVBoyOLR7DFx4sbeogWjRT+Wu89IznVtvsoR+qHyM2bfY3XX9OTaIoJBK4oZi
    62KcoisvGzxHjW2HsAZ4keEg6ZviyB39aw+AkkLV30ibkvsQ8xjMjsvoDk9kbw+O
    SkULTLKQDY9hHJX7qXuFGd4U9QKBgQDfO2tcrMcnFvwl5PrZcUbRZM6xutYaLSu+
    KjSG4OiqGMywJHA4qdKvp+qNwzGH3ghhVaq2rOx5LGiZlQbw9rbNPpP+6MUE/uz5
    O5UcWqaVyegYTAa1ih8LfmqlX6+lo36asyJ991CN9hH/jk6fB2ERD2EiqBui5I/2
    SxsAcmkAOQKBgE0rlDe663J6kXcecDzGMoDfGL89u3ExF32DzpXzWL601brxZ1cx
    f54jKaTLNZScQv0AldKqQ7gvc9TvKZQSUb5TqXEjVILE8Hfvk0OZ0wwQm/FtpWAa
    sg/R1ihpvghUariWmj8NEojH/eEAU4aWfekPoLnb/ztuRRE62OZm0vT5AoGAMDmX
    8gdpZqpygoU7I+py0B2lAYRJaJJFlulrO5Au80A0SAE3NSaK22O9Ki727lErIkvt
    e1VUKMFNP5CQVVIXH7PbKQCEP5YK/7S9e8ihoE5kE4upD2LtXgBLbbqEKZZubWEx
    nGDnSCPWs4y8s2JWt+bIp0IF5mTWLPEAvlH5GRECgYEAlUBmofySCCOg1C8WaGTK
    P+gYl7uITbyUoSHsdvcVhP4gfXywixRc3Sha1lJVCDO1NoQfWgf0+p8Dsd7TP6P8
    +IX3sj7INi6JrbY5lcISelqTpzVFoPeFu0REfUHCmOCy+PGt3TedKqN2v+nzB1JO
    Jrg3tqr1//McKrbUNZha5LU=
    -----END PRIVATE KEY-----

  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIJAPkXL2dCDVVNMA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV
    BAYTAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExEDAOBgNV
    BAoMB0dpZ2Ftb24xDDAKBgNVBAsMA1JuRDEdMBsGA1UEAwwUdGVzdHJhaWwuZ2ln
    YW1vbi5jb20wHhcNMjExMDI0MDY0OTI3WhcNMzExMDIyMDY0OTI3WjBvMQswCQYD
    VQQGEwJVUzELMAkGA1UECAwCQ0ExFDASBgNVBAcMC1NhbnRhIENsYXJhMRAwDgYD
    VQQKDAdHaWdhbW9uMQwwCgYDVQQLDANSbkQxHTAbBgNVBAMMFHRlc3RyYWlsLmdp
    Z2Ftb24uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0d347lJs
    tlVcw7h74B8OFJiZ/yd2oF+pmsU+kNUnixRgu0M979E5N3CcvVvBsAnneNgpzK23
    H0kxdflEkV4I9keN6H2klkHvMFLOp38mJcAds54t5WpVhYlOOG9T8dO2z7kcY7To
    i0jQwfxVz7d5cEi/zZTxg2tltLUYZzC8IJBNY6zZ7DRtY7HlhFVvwCHMhW3+vLPy
    QiI9xVGP9uPRo+7RJyWvSxo+MzM1yXDbylvRD4nJXN/sgwg0C/cuuMm2Kc5fZHth
    hjCaZu+SHs01QFj3k5CRIBTY/vGMTgxLevGGhS/JSlnvx1ZXdOx1ZI2RbvMpYr7X
    /bL11dkOdO+qjQIDAQABo1AwTjAdBgNVHQ4EFgQUZEy+VWCtPt5hAJcjMd+mrSMr
    GE0wHwYDVR0jBBgwFoAUZEy+VWCtPt5hAJcjMd+mrSMrGE0wDAYDVR0TBAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAfX/d1pQT6O7lwL1IeDNr6HsDdb21av6rmBdz
    +LbjQJqjxqPSlgjHlNxH14A6MEmbZL0VN9hUAXYpF+6L0SHf77siudSw9zDk9wog
    bjeK4uynOaM4hLd65kmzTtCbyRi6+LTEAPto4QLwsI9YQahTkrVQl/ZfDj41VpH5
    jWtVFB9yoMUEDh9v0g41iX2esRD+ROP2pMKSRDqTiovMSuba3Qa2dciKnn5KcBYF
    R+ngq8dYFgxmjJQ/S9Q82dc/MJFh4FgV2UKt1SUiRGdppuA5o9+LHAB7xYZ4faQI
    tdEq5o1qLLAva6zdiny+Rll6eYMGf0BAEo5oHokc9Wdc3FoVxQ==
    -----END CERTIFICATE-----


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsfront-testrail
  labels:
    app: tlsfront-testrail
spec:
  selector:
    matchLabels:
      app: tlsfront-testrail
  replicas: 2
  template:
    metadata:
      labels:
        app: tlsfront-testrail
    spec:
      containers:
      - name: tlsfront-testrail
        image: tlspack/tlsfront:latest
        imagePullPolicy: Always
        command: ["tlsfront.exe"]
        args: []
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: tlsfront-testrail-configmap


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsfront-web
  labels:
    app: tlsfront-web
spec:
  selector:
    matchLabels:
      app: tlsfront-web
  replicas: 1
  template:
    metadata:
      labels:
        app: tlsfront-web
    spec:
      containers:
      - name: tlsfront-web
        image: tlspack/tlsfront:latest
        imagePullPolicy: Always
        workingDir: /tlsfront_web/
        command: ["python3"]
        args: ["tlsfront.py"]
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: tlsfront-web-configmap


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsserver
  labels:
    app: tlsserver
spec:
  selector:
    matchLabels:
      app: tlsserver
  replicas: 1
  template:
    metadata:
      labels:
        app: tlsserver
    spec:
      containers:
      - name: tlsserver
        image: tlspack/tlsfront:latest
        imagePullPolicy: Always
        command: ["tlsserver.exe"]
        args: []
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: tlsserver-configmap


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsfront-tlsserver
  labels:
    app: tlsfront-tlsserver
spec:
  selector:
    matchLabels:
      app: tlsfront-tlsserver
  replicas: 1
  template:
    metadata:
      labels:
        app: tlsfront-tlsserver
    spec:
      containers:
      - name: tlsfront-tlsserver
        image: tlspack/tlsfront:latest
        imagePullPolicy: Always
        command: ["tlsfront.exe"]
        args: []
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: tlsfront-tlsserver-configmap


---


apiVersion: v1
kind: Service
metadata:
  name: tlsfront-testrail-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.115.30.245
  selector:
    app: tlsfront-testrail
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443


---


apiVersion: v1
kind: Service
metadata:
  name: tlsfront-web-service
spec:
  externalIPs:
  - 10.115.30.245
  selector:
    app: tlsfront-web
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: web
    - protocol: UDP
      port: 7000
      targetPort: 7000
      name: stats


---


apiVersion: v1
kind: Service
metadata:
  name: tlsserver-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.115.30.245
  selector:
    app: tlsserver
  ports:
    - protocol: TCP
      port: 88
      targetPort: 88



---


apiVersion: v1
kind: Service
metadata:
  name: tlsfront-tlsserver-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.115.30.245
  selector:
    app: tlsfront-tlsserver
  ports:
    - protocol: TCP
      port: 89
      targetPort: 89

