apiVersion: v1
kind: ConfigMap
metadata:
  name: client-001
data:
  config.json: >
    {
      "app_id" : "client-001",

      "server_ip"   : "12.20.61.1",
      "server_port" : 443,
      "server_ssl"  : 1,

      "stats_ip"   : "10.115.30.245",
      "stats_port" : 7000,

      "send_recv_len" : 1024,

      "cps": 1,
      "total_conn_count" : 0,
      "max_active_conn_count" : 10
    }

---


apiVersion: v1
kind: Pod
metadata:
  name: client-001
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "ens192",
              "ips": [ "12.20.51.1/16", "12.20.51.2/16", "12.20.51.3/16",
                       "100.20.51.1/16", "100.20.51.2/16", "100.20.51.3/16"]
            }]'
spec:
  containers:
  - name: client-001
    image: tlspack/tlsfront:latest
    imagePullPolicy: Always
    command: ["ping"]
    args: ["www.google.com"]
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    volumeMounts:
    - name: config-volume
      mountPath: /configs/
  volumes:
  - name: config-volume
    configMap:
      name: client-001 

  nodeSelector:
    tgid: a-node2
